swagger: "2.0"
info:
  version: 1.0.0
  title: myapp
  description: My Uncle Minimart
basePath: /api/v1
tags:
  - name: Products
    description: Simple product endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  ProductBody:
    type: object
    title: product
    required:
      - name
      - price
    properties:
      name:
        type: string
        minLength: 1
        example: product1
      price:
        type: number
        minimum: 0
        example: 10

paths:
  /products:
    get:
      tags:
        - Products
      description: Fetch all products
      responses:
        200:
          description: Returns all products
    post:
      tags:
        - Products
      description: Create a new product
      parameters:
        - name: product
          in: body
          description: a product
          required: true
          schema: 
            $ref: "#/definitions/ProductBody"
      responses:
        200:
          description: Returns newly created product

  /products/{id}:
    get:
      tags:
        - Products
      description: Get a product
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the product to retrieve
          type: string
      responses:
        200:
          description: Return the product with the specified id
        404:
          description: Product not found
    patch:
      tags:
        - Products
      description: Update a product
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the product to update
          type: string
        - name: product
          in: body
          description: example attribtues to update
          required: true
          schema: 
            $ref: "#/definitions/ProductBody"
      responses:
        200:
          description: Return updated products
        404:
          description: Product not found
    delete:
      tags:
        - Products
      description: Delete a product
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the product to delete
          type: string
      responses:
        204:
          description: Delete the product with the specified id
        404:
          description: Product not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification